runtime: python38 # or another supported version

instance_class: F1 # this is the cheapest option

env_variables:
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "safewalk"
  MYSQL_DB: "safewalk_la"
  MYSQL_HOST: "34.28.174.109"
# handlers:

# - url: app\frontend\src
# static_dir: app\frontend\src
# - url: app\frontend\src
# static_dir: app\frontend\src
