runtime: python38 # or another supported version

instance_class: F1 # this is the cheapest option

env_variables:
  MYSQL_USER: "fill_the_username_of_database"
  MYSQL_PASSWORD: "fill_the_password_of_database"
  MYSQL_DB: "safewalk_la"
  MYSQL_HOST: "fill_the_ip_of_database"
  MYSQL_PORT: "fill_the_port_of_database"
  MYSQL_UNIX_SOCKET: "/mysql/mysql.sock"

handlers:

- url: app/scripts
  static_dir: static/app/scripts

- url: app/styles
  static_dir: static/app/styles
