runtime: python38 # or another supported version

instance_class: F1 # this is the cheapest option

env_variables:
  MYSQL_USER:
  MYSQL_PASSWORD:
  MYSQL_DB:
  MYSQL_HOST:
  MYSQL_PORT:
  MYSQL_UNIX_SOCKET:

handlers:
  - url: app/scripts
    static_dir: static/app/scripts

  - url: app/styles
    static_dir: static/app/styles
